import { readFileSync } from "node:fs";

export interface WorkerAuthState {
  token: string;
  error?: string;
}

// The shared secret is generated by the deployment layer and mounted read-only.
// It is independent of FilmFusion's config.yaml and is reread for every request.
export function readWorkerAuthState(): WorkerAuthState {
  const path = process.env.WORKER_AUTH_TOKEN_FILE?.trim();
  if (!path) {
    return { token: "", error: "Worker Token 文件未配置" };
  }

  let raw: string;
  try {
    raw = readFileSync(path, "utf8");
  } catch {
    return { token: "", error: "Worker Token 文件不可读" };
  }

  const token = raw.trim();
  if (!token) {
    return { token: "", error: "Worker Token 未配置" };
  }
  if (/[\r\n]/.test(token)) {
    return { token: "", error: "Worker Token 格式无效" };
  }
  return { token };
}
