services:
  film-fusion:
    image: "kumayi/film-fusion:v3.0.8"
    container_name: "film-fusion"
    # restart: unless-stopped
    ports:
      # Web 管理界面和 API 端口
      - "8095:8095"
      # Emby 代理端口（用于直链播放）
      - "8097:8097"
    volumes:
      # 配置和数据目录
      - /vol3/1000/Docker/FilmFusion/data:/app/data
      # 媒体目录
      - /vol3/1000/MediaSTRM:/MediaSTRM
      - /vol1/1000/CloudNAS:/CloudNAS
      - /vol2/1000/Media:/Media
      - /vol2/1000/Media:/vol2/1000/Media
      - /vol1/1000/CloudNAS:/vol1/1000/CloudNAS
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=release

networks:
  default:
    name: film-fusion-network
